#!/bin/bash
# Quick Start Guide - EMS Refactored Role-Based System

echo "=== EMS Role-Based System - Implementation Guide ==="
echo ""

echo "Step 1: Database Migration"
echo "  - Execute DATABASE_MIGRATION.sql in your database"
echo "  - Verify data migrated successfully"
echo "  - Check indexes created"
echo ""

echo "Step 2: Build Project"
echo "  mvn clean install"
echo ""

echo "Step 3: Run Application"
echo "  mvn spring-boot:run"
echo "  # Application should start on http://localhost:8080"
echo ""

echo "Step 4: Test Registration"
echo "  curl -X POST http://localhost:8080/auth/register \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{"
echo "      \"username\": \"john.doe\","
echo "      \"email\": \"john@example.com\","
echo "      \"password\": \"password123\","
echo "      \"firstName\": \"John\","
echo "      \"lastName\": \"Doe\","
echo "      \"role\": \"EMPLOYEE\""
echo "    }'"
echo ""

echo "Step 5: Test Login"
echo "  curl -X POST http://localhost:8080/auth/login \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{"
echo "      \"eid\": \"E001\","
echo "      \"password\": \"password123\""
echo "    }'"
echo ""

echo "=== Key Information ==="
echo ""
echo "User Roles:"
echo "  - ADMIN (prefix: A) - System administrators"
echo "  - TECHNICIAN (prefix: T) - Support technicians"
echo "  - EMPLOYEE (prefix: E) - Regular employees"
echo ""

echo "EID Format (Auto-generated):"
echo "  - E001, E002, ... (Employees)"
echo "  - T001, T002, ... (Technicians)"
echo "  - A001, A002, ... (Admins)"
echo ""

echo "Key Services:"
echo "  - UserService: Centralized user management"
echo "  - EIDGeneratorService: Sequential EID generation"
echo "  - CustomUserDetailsService: Spring Security integration"
echo ""

echo "Key Repositories:"
echo "  - UserRepository: Primary user access"
echo "  - EmployeRepository: Find employees (backward compatible)"
echo "  - TechnicianRepository: Find technicians (backward compatible)"
echo "  - AdministratorRepository: Find admins (backward compatible)"
echo ""

echo "API Endpoints:"
echo "  POST   /auth/login           - User login (returns JWT token)"
echo "  POST   /auth/register        - User registration"
echo "  GET    /admin/**             - Admin endpoints (@PreAuthorize)"
echo "  GET    /technician/**        - Technician endpoints (@PreAuthorize)"
echo "  GET    /employee/**          - Employee endpoints (@PreAuthorize)"
echo ""

echo "=== Troubleshooting ==="
echo ""
echo "Issue: Column 'eid' doesn't exist"
echo "  Fix: Run DATABASE_MIGRATION.sql to migrate schema"
echo ""

echo "Issue: findByEID() method not found"
echo "  Fix: Use findByEid() instead (camelCase)"
echo ""

echo "Issue: Cannot instantiate Employe class"
echo "  Fix: Use UserService.registerEmployee() or new User()"
echo ""

echo "Issue: Role-based access denied"
echo "  Fix: Check @PreAuthorize annotation uses ROLE_* format"
echo "       UserDetails must have ROLE_ADMIN, ROLE_TECHNICIAN, ROLE_EMPLOYEE"
echo ""

echo "=== Project Structure ==="
echo ""
echo "Entities:"
echo "  - User (single entity, no inheritance)"
echo "  - Role (enum: ADMIN, TECHNICIAN, EMPLOYEE)"
echo "  - Ticket, Leave, Comment, TicketHistory, etc."
echo ""

echo "Services:"
echo "  - UserService (primary user management)"
echo "  - EIDGeneratorService (EID generation)"
echo "  - CustomUserDetailsService (Spring Security)"
echo ""

echo "Controllers:"
echo "  - AuthController (/auth/login, /auth/register)"
echo "  - Other controllers using @PreAuthorize"
echo ""

echo "Repositories:"
echo "  - UserRepository (primary)"
echo "  - Legacy: EmployeRepository, TechnicianRepository, AdministratorRepository"
echo ""

echo "=== Next Steps ==="
echo ""
echo "1. Run DATABASE_MIGRATION.sql"
echo "2. mvn clean install"
echo "3. mvn spring-boot:run"
echo "4. Test endpoints with curl or Postman"
echo "5. Delete obsolete classes if desired (Administrator, Employe, Technician)"
echo ""

echo "✅ Setup complete! Your EMS is now using a production-ready role-based system."
